model_list:
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: ollama/gemma4:26b
      api_base: https://ollama.mdes-innova.online
      api_key: !os.environ "OLLAMA_TOKEN"

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: ollama/gemma4:26b
      api_base: https://ollama.mdes-innova.online
      api_key: !os.environ "OLLAMA_TOKEN"

  - model_name: claude-opus-4-8
    litellm_params:
      model: ollama/gemma4:26b
      api_base: https://ollama.mdes-innova.online
      api_key: !os.environ "OLLAMA_TOKEN"

litellm_settings:
  drop_params: true
  set_verbose: false
  max_tokens: 2048
